#!/usr/bin/env bash
set -euo pipefail

# ─── vllm-toolchest setup ──────────────────────────────────────────
# Detects GPU, container runtime, and launches vllm-toolchest.

BOLD='\033[1m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
RED='\033[0;31m'
NC='\033[0m'

info()  { echo -e "${GREEN}[INFO]${NC} $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*"; }

# ─── GPU Detection ─────────────────────────────────────────────────
detect_gpu() {
    if command -v nvidia-smi &>/dev/null && nvidia-smi &>/dev/null; then
        GPU_TYPE="cuda"
        GPU_NAME=$(nvidia-smi --query-gpu=name --format=csv,noheader | head -1)
        GPU_COUNT=$(nvidia-smi --query-gpu=name --format=csv,noheader | wc -l)
        info "Detected NVIDIA GPU: ${GPU_NAME} (${GPU_COUNT} GPU(s))"
    elif [ -e /dev/kfd ]; then
        GPU_TYPE="rocm"
        if command -v rocminfo &>/dev/null; then
            GPU_NAME=$(rocminfo 2>/dev/null | grep "Marketing Name" | grep -v "AMD Ryzen\|AMD EPYC" | head -1 | sed 's/.*Marketing Name:\s*//')
        else
            GPU_NAME="AMD GPU"
        fi
        GPU_COUNT=$(ls /dev/dri/renderD* 2>/dev/null | wc -l)
        info "Detected AMD GPU: ${GPU_NAME} (${GPU_COUNT} render node(s))"
    else
        GPU_TYPE="none"
        GPU_NAME="None detected"
        GPU_COUNT=0
        warn "No GPU detected. vLLM requires a GPU to run inference."
    fi
}

# ─── Container Runtime Detection ───────────────────────────────────
detect_runtime() {
    if command -v docker &>/dev/null; then
        RUNTIME="docker"
        COMPOSE_CMD="docker compose"
        # Check if docker compose plugin is available
        if ! docker compose version &>/dev/null; then
            if command -v docker-compose &>/dev/null; then
                COMPOSE_CMD="docker-compose"
            else
                error "docker compose plugin not found. Install with: sudo apt install docker-compose-plugin"
                exit 1
            fi
        fi
        info "Container runtime: Docker (${COMPOSE_CMD})"
    elif command -v podman &>/dev/null; then
        RUNTIME="podman"
        if command -v podman-compose &>/dev/null; then
            COMPOSE_CMD="podman-compose"
        else
            error "podman-compose not found. Install with: pip install podman-compose"
            exit 1
        fi
        info "Container runtime: Podman (${COMPOSE_CMD})"
    else
        error "No container runtime found. Install Docker or Podman first."
        echo ""
        echo "Docker:  https://docs.docker.com/engine/install/"
        echo "Podman:  https://podman.io/docs/installation"
        exit 1
    fi
}

# ─── NVIDIA-specific setup ─────────────────────────────────────────
setup_nvidia() {
    # Check for NVIDIA Container Toolkit
    if ! command -v nvidia-container-cli &>/dev/null; then
        warn "NVIDIA Container Toolkit not detected."
        echo ""
        echo "Install it from: https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html"
        echo ""
        read -p "Continue anyway? (y/N) " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            exit 1
        fi
    else
        info "NVIDIA Container Toolkit detected."
    fi
}

# ─── AMD-specific setup ───────────────────────────────────────────
setup_amd() {
    # Check group membership
    if ! id -nG | grep -qw video; then
        warn "Current user is not in the 'video' group."
        echo "  Run: sudo usermod -aG video \$USER"
    fi
    if ! id -nG | grep -qw render; then
        warn "Current user is not in the 'render' group."
        echo "  Run: sudo usermod -aG render \$USER"
    fi

    # Get group GIDs for compose
    HOST_VIDEO_GID=$(getent group video 2>/dev/null | cut -d: -f3 || echo "video")
    HOST_RENDER_GID=$(getent group render 2>/dev/null | cut -d: -f3 || echo "render")
}

# ─── Generate .env ────────────────────────────────────────────────
generate_env() {
    if [ -f .env ]; then
        info ".env file already exists, not overwriting."
        return
    fi

    cat > .env << EOF
# Generated by setup.sh on $(date -Iseconds)
# GPU: ${GPU_TYPE} - ${GPU_NAME}

VLLMCTL_PORT=3000
VLLMCTL_INFERENCE_PORT=8000
EOF

    if [ "${GPU_TYPE}" = "rocm" ]; then
        cat >> .env << EOF

# AMD ROCm settings
HOST_VIDEO_GID=${HOST_VIDEO_GID:-video}
HOST_RENDER_GID=${HOST_RENDER_GID:-render}
EOF
    fi

    info "Generated .env file."
}

# ─── Select compose file ──────────────────────────────────────────
select_compose() {
    case "${GPU_TYPE}" in
        cuda)
            COMPOSE_FILE="docker-compose.cuda.yml"
            ;;
        rocm)
            COMPOSE_FILE="docker-compose.yml"
            ;;
        *)
            warn "No GPU detected. Using CUDA compose file (will fail without GPU)."
            COMPOSE_FILE="docker-compose.cuda.yml"
            ;;
    esac
    info "Using compose file: ${COMPOSE_FILE}"
}

# ─── Build and launch ─────────────────────────────────────────────
build_and_launch() {
    echo ""
    echo -e "${BOLD}Building container image...${NC}"
    echo "This may take a while (especially the first time)."
    echo ""

    ${COMPOSE_CMD} -f "${COMPOSE_FILE}" build

    echo ""
    echo -e "${BOLD}Starting vllm-toolchest...${NC}"
    ${COMPOSE_CMD} -f "${COMPOSE_FILE}" up -d

    # Wait for health check
    echo ""
    info "Waiting for vllm-toolchest to start..."
    for i in $(seq 1 30); do
        if curl -sf http://localhost:3000/healthz >/dev/null 2>&1; then
            echo ""
            echo -e "${GREEN}${BOLD}vllm-toolchest is running!${NC}"
            echo ""
            echo "  Web UI:  http://localhost:3000"
            echo "  API:     http://localhost:3000/v1"
            echo ""
            echo "  Logs:    ${COMPOSE_CMD} -f ${COMPOSE_FILE} logs -f"
            echo "  Stop:    ${COMPOSE_CMD} -f ${COMPOSE_FILE} down"
            echo ""
            return
        fi
        sleep 1
        echo -n "."
    done

    echo ""
    warn "Health check timed out. Container may still be starting."
    echo "Check logs: ${COMPOSE_CMD} -f ${COMPOSE_FILE} logs -f"
}

# ─── Main ─────────────────────────────────────────────────────────
main() {
    echo -e "${BOLD}vllm-toolchest setup${NC}"
    echo ""

    detect_gpu
    detect_runtime

    case "${GPU_TYPE}" in
        cuda)  setup_nvidia ;;
        rocm)  setup_amd ;;
    esac

    select_compose
    generate_env
    build_and_launch
}

main "$@"
